name: node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: cd server
                  npm install
                  cd ..
                  cd client
                  npm install
                  npm run build
                  cd ..
                  pm2 stop 0
                  pm2 start 0
                  pm2 save
                  sudo service nginx restart
